### ISSUE TITLE
Standard components

### ISSUE THREAD

**Issue by diogomqbm** [t10d/cra-template-kingdom#12]
# Description
I think we should build some standard components to increase DX with this boilerplate. I was thinking about building a generic:

- [x] Input
- [x] Button
- [x] Select 

What do you guys think?

**Comment by GuilhermeLLS** [comment]
@diogomqbm @leonardomolinan @phenrique7 @luisrondow @AgmarTorres @frostbig @marianaks 

We need to pick an icon library. ChakraUI has its own icon lib, but there are many other options such as react-icons, react-feather, etc. 

Any suggestions?

**Comment by luisrondow** [comment]
I think to default icons we can use Chackra UI Icons. In other projects, this decision is up to the designers.

**Comment by AgmarTorres** [comment]
Top, another possibility that we could consider would be the Material-UI, it is very simple to use as well and the repository is very vast and dynamic.

**Comment by diogomqbm** [comment]
I changed the description because we can implement NavBar and Autocomplete in further changes

**Comment by diogomqbm** [comment]
closed by #24
