### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by diogomqbm** [t10d/cra-template-kingdom#2]
# Description
Regarding linting and code style we should choose which configuration and patterns to use. I'm good with using any current project linting pattern such as Apolo's. What do you guys think?

**Comment by leonardomolinan** [comment]
If Apolo's linting pattern are the best of we have today on T10 I think that we can use the same patterns, otherwise we can find another one, that will need to be better than the first in some way.

**Comment by GuilhermeLLS** [comment]
this is not a big deal for me. As long as those patterns get respected, I am down to do anything.

**Comment by diogomqbm** [comment]
Me too

**Comment by luisrondow** [comment]
I like 2 spaces + semicolon + single quotes. I think we can use some pattern.
