### ISSUE TITLE
Form and Validations

### ISSUE THREAD

**Issue by luisrondow** [t10d/cra-template-kingdom#4]
## Description

Here we can discuss which is the best Form implementation in React. We should define the Form lib and how we gonna implement the validations.

In my vision, there are 2 great Form libs:
- [Formik](https://formik.org/)
- [React Hook Form](https://react-hook-form.com/)

And for validations, I think the best alternative is use [Yup](https://github.com/jquense/yup).

What do you think about that?

**Comment by diogomqbm** [comment]
I'm all in for React Hook Form! Doesn't RHF handle validation? Or we need a third-party like Yup for it?

**Comment by phenrique7** [comment]
React Hook Form ftw! I don't think it is necessary to bring Yup to the template. Although Yup has better validation compositions/abstractions, it fits better with Formik, as it has integration with it. RHF has simpler, but more manual, validation compositions/abstractions, and for some cases, it is enough. I think that at a higher level of scalability or complexity of validations it will be worthwhile to bring Yup together with RHF.

**Comment by GuilhermeLLS** [comment]
I think we have a consense regarding React Hook Form. Do you guys have any suggestion about how to implement the validations for this form and the form UI itself?

**Comment by phenrique7** [comment]
> I think we have a consense regarding React Hook Form. Do you guys have any suggestion about how to implement the validations for this form and the form UI itself?

If the [documentation](https://react-hook-form.com/get-started) is not enough for you, maybe some form implementations with validation in the [Apolo project](https://github.com/t10d/apolo-front/search?q=useForm) can be useful (be aware that we are using RHF v6, so far).

Note: [RHF v7](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.0.0) was released recently.

**Comment by GuilhermeLLS** [comment]
I've used v7 this weekend on a personal project, it seems pretty good overall, although i've never used v6 and below. @phenrique7 

I'm thinking about self-assigning this issue. Does anyone else want to be a part of the development proccess?

@diogomqbm  @leonardomolinan @AgmarTorres @marianaks @frostbig @luisrondow

**Comment by phenrique7** [comment]
@GuilhermeLLS, what do you have in mind to be added to the template for this part of forms?

**Comment by GuilhermeLLS** [comment]
@phenrique7  
Me and @diogomqbm  thought about inserting a job application form in the template. It would be something like an "EasterEgg", we were inspired by Discord and Medium. (When you open the Dev Console on those sites or desktop applications, there is a link to the careers page).

However, as we are using Gupy for recruitment, we dismiss this idea. Now, I have nothing in mind, neither validations nor the UI itself. Perhaps we could create some validations for the most used cases, such as phone number, CEP, CPF. What do you think?

**Comment by phenrique7** [comment]
> @phenrique7
> Me and @diogomqbm thought about inserting a job application form in the template. It would be something like an "EasterEgg", we were inspired by Discord and Medium. (When you open the Dev Console on those sites or desktop applications, there is a link to the careers page).
> 
> However, as we are using Gupy for recruitment, we dismiss this idea. Now, I have nothing in mind, neither validations nor the UI itself. Perhaps we could create some validations for the most used cases, such as phone number, CEP, CPF. Or since the form input fields are something specific to each project, we can simply install RHF and don't make any other changes at all.
> 
> What do you think?

SPA applications generally assume the use of login interfaces, which would include the implementation of forms. As it is a template, I think it is interesting to have a page with a simple login form, with email and password inputs, and with basic initial validations using RHF.

**Comment by diogomqbm** [comment]
@GuilhermeLLS @phenrique7 I think we should implement every screen regarding system access. In practice, we should implement login, reset password, and register screen. I also think we can implement a profile screen inside the authenticated app.
